JOB START DT : '2018-10-31 05:14:19' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:14:34' | STATUS : [Error] Failed
JOB START DT : '2018-10-31 05:14:19' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:14:34' | STATUS : 
 __main__ JB_PRODUCT_BOOKING_REPORT --> Exception-Traceback :: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, 10.103.164.240, executor 5): ExecutorLostFailure (executor 5 exited caused by one of the running tasks) Reason: Unable to create executor due to Exception thrown in awaitResult: 
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1602)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1590)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1589)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1589)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1823)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1772)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1761)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2055)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2074)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:939)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:938)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:162)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

JOB START DT : '2018-10-31 05:15:21' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:15:30' | STATUS : [Error] Failed
JOB START DT : '2018-10-31 05:15:21' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:15:30' | STATUS : 
 __main__ JB_PRODUCT_BOOKING_REPORT --> Exception-Traceback :: ORA-00907: missing right parenthesis
JOB START DT : '2018-10-31 05:19:26' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:19:28' | STATUS : [Error] Failed
JOB START DT : '2018-10-31 05:19:26' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:19:28' | STATUS : 
 __main__ JB_PRODUCT_BOOKING_REPORT --> Exception-Traceback :: name 'param_fiscal_month' is not defined
JOB START DT : '2018-10-31 05:24:00' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:24:02' | STATUS : [Error] Failed
JOB START DT : '2018-10-31 05:24:00' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:24:02' | STATUS : 
 __main__ JB_PRODUCT_BOOKING_REPORT --> Exception-Traceback :: query_data() missing 2 required positional arguments: 'Param_fiscal_month' and 'Param_fiscal_year_quarter'
JOB START DT : '2018-10-31 05:25:41' | SCRIPT NAME : SCH1101.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 05:46:28' | STATUS : Success
JOB START DT : '2018-10-31 21:58:44' | SCRIPT NAME : SCH1160.SH | JOB : JB_PRODUCT_BOOKING_REPORT | SRC COUNT : 0 | TGT COUNT : 0 | JOB END DT : '2018-10-31 22:12:50' | STATUS : Success
